name: fortnite_api
description: Fortnite Api Wrapper.
version: 0.0.1
author: André Varandas
homepage: https://github.com/AndreVarandas/dart-fortnite-api-wrapper
repository: https://github.com/AndreVarandas/dart-fortnite-api-wrapper
issue_tracker: https://github.com/AndreVarandas/dart-fortnite-api-wrapper/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
